# Generated by Django 5.2.2 on 2025-06-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_colorvariant_sizevariant_product_color_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizevariant",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
