# Generated by Django 5.2.2 on 2025-06-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_sizevariant_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color_variant",
            field=models.ManyToManyField(blank=True, to="products.colorvariant"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size_variant",
            field=models.ManyToManyField(blank=True, to="products.sizevariant"),
        ),
    ]
